/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'YYM' at '15-12-20 下午4:46' with Gradle 2.5-rc-2
 *
 * @author YYM, @date 15-12-20 下午4:46
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
